#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentCMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ContentCMSDB")]
	public partial class contentCMSDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertpage(page instance);
    partial void Updatepage(page instance);
    partial void Deletepage(page instance);
    #endregion
		
		public contentCMSDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ContentCMSDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public contentCMSDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public contentCMSDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public contentCMSDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public contentCMSDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<page> pages
		{
			get
			{
				return this.GetTable<page>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pages")]
	public partial class page : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pageID;
		
		private string _pageURL;
		
		private string _pageTitle;
		
		private string _pageContent;
		
		private System.Nullable<System.DateTime> _lastUpdate;
		
		private bool _isPublished;
		
		private int _parent;
		
		private bool _isContent;
		
		private bool _isStatic;
		
		private System.Nullable<System.Guid> _author;
		
		private System.Nullable<int> _pageOrder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpageIDChanging(int value);
    partial void OnpageIDChanged();
    partial void OnpageURLChanging(string value);
    partial void OnpageURLChanged();
    partial void OnpageTitleChanging(string value);
    partial void OnpageTitleChanged();
    partial void OnpageContentChanging(string value);
    partial void OnpageContentChanged();
    partial void OnlastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastUpdateChanged();
    partial void OnisPublishedChanging(bool value);
    partial void OnisPublishedChanged();
    partial void OnparentChanging(int value);
    partial void OnparentChanged();
    partial void OnisContentChanging(bool value);
    partial void OnisContentChanged();
    partial void OnisStaticChanging(bool value);
    partial void OnisStaticChanged();
    partial void OnauthorChanging(System.Nullable<System.Guid> value);
    partial void OnauthorChanged();
    partial void OnpageOrderChanging(System.Nullable<int> value);
    partial void OnpageOrderChanged();
    #endregion
		
		public page()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pageID
		{
			get
			{
				return this._pageID;
			}
			set
			{
				if ((this._pageID != value))
				{
					this.OnpageIDChanging(value);
					this.SendPropertyChanging();
					this._pageID = value;
					this.SendPropertyChanged("pageID");
					this.OnpageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageURL", DbType="VarChar(100)")]
		public string pageURL
		{
			get
			{
				return this._pageURL;
			}
			set
			{
				if ((this._pageURL != value))
				{
					this.OnpageURLChanging(value);
					this.SendPropertyChanging();
					this._pageURL = value;
					this.SendPropertyChanged("pageURL");
					this.OnpageURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageTitle", DbType="VarChar(100)")]
		public string pageTitle
		{
			get
			{
				return this._pageTitle;
			}
			set
			{
				if ((this._pageTitle != value))
				{
					this.OnpageTitleChanging(value);
					this.SendPropertyChanging();
					this._pageTitle = value;
					this.SendPropertyChanged("pageTitle");
					this.OnpageTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageContent", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string pageContent
		{
			get
			{
				return this._pageContent;
			}
			set
			{
				if ((this._pageContent != value))
				{
					this.OnpageContentChanging(value);
					this.SendPropertyChanging();
					this._pageContent = value;
					this.SendPropertyChanged("pageContent");
					this.OnpageContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastUpdate
		{
			get
			{
				return this._lastUpdate;
			}
			set
			{
				if ((this._lastUpdate != value))
				{
					this.OnlastUpdateChanging(value);
					this.SendPropertyChanging();
					this._lastUpdate = value;
					this.SendPropertyChanged("lastUpdate");
					this.OnlastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPublished", DbType="Bit NOT NULL")]
		public bool isPublished
		{
			get
			{
				return this._isPublished;
			}
			set
			{
				if ((this._isPublished != value))
				{
					this.OnisPublishedChanging(value);
					this.SendPropertyChanging();
					this._isPublished = value;
					this.SendPropertyChanged("isPublished");
					this.OnisPublishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="Int NOT NULL")]
		public int parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isContent", DbType="Bit NOT NULL")]
		public bool isContent
		{
			get
			{
				return this._isContent;
			}
			set
			{
				if ((this._isContent != value))
				{
					this.OnisContentChanging(value);
					this.SendPropertyChanging();
					this._isContent = value;
					this.SendPropertyChanged("isContent");
					this.OnisContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isStatic", DbType="Bit NOT NULL")]
		public bool isStatic
		{
			get
			{
				return this._isStatic;
			}
			set
			{
				if ((this._isStatic != value))
				{
					this.OnisStaticChanging(value);
					this.SendPropertyChanging();
					this._isStatic = value;
					this.SendPropertyChanged("isStatic");
					this.OnisStaticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this.OnauthorChanging(value);
					this.SendPropertyChanging();
					this._author = value;
					this.SendPropertyChanged("author");
					this.OnauthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageOrder", DbType="Int")]
		public System.Nullable<int> pageOrder
		{
			get
			{
				return this._pageOrder;
			}
			set
			{
				if ((this._pageOrder != value))
				{
					this.OnpageOrderChanging(value);
					this.SendPropertyChanging();
					this._pageOrder = value;
					this.SendPropertyChanged("pageOrder");
					this.OnpageOrderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
